openapi: "3.0.3"
info:
  description: "Decentralized Identity Foundation Presentation Exchange API"
  version: "1.0.0"
  title: "DIF PE API"
  contact:
    email: "you@your-company.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /presentation_definition:
    get:
      summary: "gets presentation definition"
      responses:
        200:
          description: "search results matching criteria"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/presentation_definition"
        400:
          description: "bad input parameter"
components:
  schemas:
    presentation_definition:
      title: "Presentation Definition"
      description: "Presentation Definitions are objects that articulate what proofs a Verifier requires."
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        purpose:
          type: "string"
          description: "It describes the purpose for which the Presentation Definition's inputs are being requested."
        format:
          title: "Format"
          description: "What claim variants Verifiers and Holders support."
          type: "object"
          oneOf:
            - type: "object"
              properties:
                alg:
                  type: "array"
                  minItems: 1
                  items:
                    type: "string"
              required:
                - "alg"
              additionalProperties: false
            - type: "object"
              properties:
                alg:
                  type: "array"
                  minItems: 1
                  items:
                    type: "string"
              required:
                - "alg"
              additionalProperties: false
            - type: "object"
              properties:
                alg:
                  type: "array"
                  minItems: 1
                  items:
                    type: "string"
              required:
                - "alg"
              additionalProperties: false
            - type: "object"
              properties:
                proof_type:
                  type: "array"
                  minItems: 1
                  items:
                    type: "string"
              required:
                - "proof_type"
              additionalProperties: false
            - type: "object"
              properties:
                proof_type:
                  type: "array"
                  minItems: 1
                  items:
                    type: "string"
              required:
                - "proof_type"
              additionalProperties: false
            - type: "object"
              properties:
                proof_type:
                  type: "array"
                  minItems: 1
                  items:
                    type: "string"
              required:
                - "proof_type"
              additionalProperties: false
          additionalProperties: false
        submission_requirements:
          type: "array"
          items:
            title: "Submission Requirements"
            description: "It defines what combinations of inputs a processing entity must submit to comply with the requirements of a Verifier."
            type: "object"
            oneOf:
              - properties:
                  name:
                    type: "string"
                  purpose:
                    type: "string"
                  rule:
                    type: "string"
                    enum:
                      - "all"
                      - "pick"
                  count:
                    type: "integer"
                    minimum: 1
                  min:
                    type: "integer"
                    minimum: 0
                  max:
                    type: "integer"
                    minimum: 0
                  from:
                    type: "string"
                required:
                  - "rule"
                  - "from"
                additionalProperties: false
              - properties:
                  name:
                    type: "string"
                  purpose:
                    type: "string"
                  rule:
                    type: "string"
                    enum:
                      - "all"
                      - "pick"
                  count:
                    type: "integer"
                    minimum: 1
                  min:
                    type: "integer"
                    minimum: 0
                  max:
                    type: "integer"
                    minimum: 0
                  from_nested:
                    type: "array"
                    minItems: 1
                    items:
                      $ref: "./resources/swagger/schemas/submission_requirement.yaml#/submission_requirements"
                required:
                  - "rule"
                  - "from_nested"
                additionalProperties: false
        input_descriptors:
          type: "array"
          items:
            title: "Input Descriptor"
            description: "Input Descriptors are used by a Verifier to describe the information required of a Holder before an interaction can proceed."
            type: "object"
            properties:
              id:
                type: "string"
              name:
                type: "string"
              purpose:
                type: "string"
                description: "It describes the purpose for which the Presentation Definition's inputs are being requested."
              group:
                type: "array"
                description: "A group from which the specific credential is required."
                items:
                  type: "string"
              schema:
                type: "array"
                items:
                  title: "Schema"
                  type: "object"
                  properties:
                    uri:
                      type: "string"
                    required:
                      type: "boolean"
                  required:
                    - "uri"
                  additionalProperties: false
              constraints:
                description: "Describes the constraints from Verifier that should be followed by Holder."
                type: "object"
                properties:
                  limit_disclosure:
                    description: "Allowes the Verifier to convey to Holder to see which properties are required and what optional credentials can be ommitted if desired by Holder."
                    type: "string"
                    enum:
                      - "required"
                      - "preferred"
                  statuses:
                    type: "object"
                    properties:
                      active:
                        type: "object"
                        properties:
                          directive:
                            type: "string"
                            enum:
                              - "required"
                              - "allowed"
                              - "disallowed"
                      suspended:
                        type: "object"
                        properties:
                          directive:
                            type: "string"
                            enum:
                              - "required"
                              - "allowed"
                              - "disallowed"
                      revoked:
                        type: "object"
                        properties:
                          directive:
                            type: "string"
                            enum:
                              - "required"
                              - "allowed"
                              - "disallowed"
                  fields:
                    type: "array"
                    items:
                      title: "Field"
                      description: "Fields required by Verifier to be submitted by Holder."
                      type: "object"
                      oneOf:
                        - properties:
                            id:
                              type: "string"
                            path:
                              type: "array"
                              items:
                                type: "string"
                            purpose:
                              type: "string"
                            filter:
                              title: "Filter"
                              type: "object"
                              properties:
                                type:
                                  type: "string"
                                format:
                                  type: "string"
                                pattern:
                                  type: "string"
                                minimum:
                                  type:
                                    - "number"
                                    - "string"
                                minLength:
                                  type: "integer"
                                maxLength:
                                  type: "integer"
                                exclusiveMinimum:
                                  type:
                                    - "number"
                                    - "string"
                                exclusiveMaximum:
                                  type:
                                    - "number"
                                    - "string"
                                maximum:
                                  type:
                                    - "number"
                                    - "string"
                                const:
                                  type:
                                    - "number"
                                    - "string"
                                enum:
                                  type: "array"
                                  items:
                                    type:
                                      - "number"
                                      - "string"
                                not:
                                  type: "object"
                                  minProperties: 1
                              required:
                                - "type"
                              additionalProperties: false
                          required:
                            - "path"
                          additionalProperties: false
                        - properties:
                            id:
                              type: "string"
                            path:
                              type: "array"
                              items:
                                type: "string"
                            purpose:
                              type: "string"
                            filter:
                              title: "Filter"
                              type: "object"
                              properties:
                                type:
                                  type: "string"
                                format:
                                  type: "string"
                                pattern:
                                  type: "string"
                                minimum:
                                  type:
                                    - "number"
                                    - "string"
                                minLength:
                                  type: "integer"
                                maxLength:
                                  type: "integer"
                                exclusiveMinimum:
                                  type:
                                    - "number"
                                    - "string"
                                exclusiveMaximum:
                                  type:
                                    - "number"
                                    - "string"
                                maximum:
                                  type:
                                    - "number"
                                    - "string"
                                const:
                                  type:
                                    - "number"
                                    - "string"
                                enum:
                                  type: "array"
                                  items:
                                    type:
                                      - "number"
                                      - "string"
                                not:
                                  type: "object"
                                  minProperties: 1
                              required:
                                - "type"
                              additionalProperties: false
                            predicate:
                              type: "string"
                              enum:
                                - "required"
                                - "preferred"
                          required:
                            - "path"
                            - "filter"
                            - "predicate"
                          additionalProperties: false
                  subject_is_issuer:
                    type: "string"
                    enum:
                      - "required"
                      - "preferred"
                  is_holder:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        field_id:
                          type: "array"
                          items:
                            type: "string"
                        directive:
                          type: "string"
                          enum:
                            - "required"
                            - "preferred"
                      required:
                        - "field_id"
                        - "directive"
                      additionalProperties: false
                  same_subject:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        field_id:
                          type: "array"
                          items:
                            type: "string"
                        directive:
                          type: "string"
                          enum:
                            - "required"
                            - "preferred"
                      required:
                        - "field_id"
                        - "directive"
                      additionalProperties: false
                additionalProperties: false
            required:
              - "id"
              - "schema"
            additionalProperties: false
      required:
        - "id"
        - "input_descriptors"
      additionalProperties: false
    presentation_submission:
      title: "Presentation Submission"
      description: "It express how the inputs presented as proofs to a Verifier."
      type: "object"
      properties:
        submission_requirements:
          title: "Submission Requirements"
          description: "It defines what combinations of inputs a processing entity must submit to comply with the requirements of a Verifier."
          type: "object"
          oneOf:
            - properties:
                name:
                  type: "string"
                purpose:
                  type: "string"
                rule:
                  type: "string"
                  enum:
                    - "all"
                    - "pick"
                count:
                  type: "integer"
                  minimum: 1
                min:
                  type: "integer"
                  minimum: 0
                max:
                  type: "integer"
                  minimum: 0
                from:
                  type: "string"
              required:
                - "rule"
                - "from"
              additionalProperties: false
            - properties:
                name:
                  type: "string"
                purpose:
                  type: "string"
                rule:
                  type: "string"
                  enum:
                    - "all"
                    - "pick"
                count:
                  type: "integer"
                  minimum: 1
                min:
                  type: "integer"
                  minimum: 0
                max:
                  type: "integer"
                  minimum: 0
                from_nested:
                  type: "array"
                  minItems: 1
                  items:
                    $ref: "./resources/swagger/schemas/submission_requirement.yaml#/submission_requirements"
              required:
                - "rule"
                - "from_nested"
              additionalProperties: false
      required:
        - "submission_requirements"
      additionalProperties: false
