openapi: 3.0.3
info:
  description: Presentation Exchange API
  version: '2.1.1'
  title: Presentation Exchange API
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: '{protocol}://{environment}.{projectName}.sphereon.io:{port}/pe'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        default: api.dev    # Development server
        enum:
          - api         # Production server
          - api.dev     # Development server
          - api.staging # Staging server
      projectName:
        default: pex
        description: Presentation Exchange API
      port:
        enum:
          - '443'
          - '8443'
        default: '443'

paths:
  /v1/threads:
    $ref: './api/v1/threads.yaml'

  /v1/definitions:
    $ref: './api/v1/definitions.yaml'
  /v1/definitions/{definition_id}:
    $ref: './api/v1/definition.yaml'
  /v1/definitions/{definition_id}/statuses:
    $ref: './api/v1/definition_statuses.yaml'

  /v1/presentations:
    $ref: './api/v1/presentations.yaml'
  /v1/presentations/{presentation_id}:
    $ref: './api/v1/presentation.yaml'
  /v1/presentations/{presentation_id}/statuses:
    $ref: './api/v1/presentation_statuses.yaml'
